name: Docker Release and Run Benchmarks
on:
  push:
    branches:
      - "master"
jobs:
  run-benchmarks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Set env
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:10}
      - name: Run benchmarks
        id: run_benchmarks
        uses: Sammers21/benchmarks@imrpove
        with:
          aws-access-key: '${{ secrets.PERF_AWS_ACCESS_KEY }}'
          aws-secret-key: '${{ secrets.PERF_AWS_SECRET_KEY }}'
          version: 'latest'
      - name: Commit benchmark results
        run: |
          set -x
          pwd
          export REPORT=${{ steps.run_benchmarks.outputs.report }}
          cat $REPORT
          export VERSION=0.9
          mkdir -p benchmarks/$VERSION
          mv $REPORT benchmarks/$VERSION/
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add benchmarks/$VERSION/$REPORT
          git commit -m "Add benchmark results for version=$VERSION"
      - name: Push benchmark results
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'gh-pages'
